# Generated by Django 4.1 on 2022-08-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
            ],
        ),
    ]
